### ISSUE TITLE
PI controller

### ISSUE THREAD

**Issue by Baokangwen** [epics-motor/motorPI#8]
Dear @MarkRivers 

Can this module be use for PI C-887 Controller？

Best wishes,

Kangwen

**Comment by MarkRivers** [comment]
@Baokangwen I don't know, I have not used the PI driver.

**Comment by kmpeters** [comment]
@Baokangwen, the C-887 controller is supported by the motorPIGCS2 module:

https://github.com/epics-motor/motorPIGCS2
